#####官方解析
####
###type
cms
###分类
官方解析
###标题
江湖官采
###图片
http://113.107.160.110:39000/tupian.php?text=江湖官采
###BaseURL
"http://119.29.1.173/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
官方解析
###标题
6U资源
###图片
http://113.107.160.110:39000/tupian.php?text=6U资源
###BaseURL
"http://www.6uzy.cc/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
官方解析
###标题
555资源
###图片
http://113.107.160.110:39000/tupian.php?text=555资源
###BaseURL
"https://www.555ziyuan.com:555/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
官方解析
###标题
天堂资源
###图片
http://113.107.160.110:39000/tupian.php?text=天堂资源
###BaseURL
"http://vipmv.cc/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
官方解析
###标题
搬运工
###图片
http://113.107.160.110:39000/tupian.php?text=搬运工
###BaseURL
"https://cj.banyung.xyz/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
官方解析
###标题
小猫咪
###图片
http://113.107.160.110:39000/tupian.php?text=小猫咪
###BaseURL
"http://zy.xiaomaomi.cc/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
官方解析
###标题
忆梦
###图片
http://113.107.160.110:39000/tupian.php?text=忆梦
###BaseURL
"http://anltv.cn/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
官方解析
###标题
江南资源
###图片
http://113.107.160.110:39000/tupian.php?text=江南资源
###BaseURL
"https://api.yjiexi.com/provide/xml.html";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
官方解析
###标题
千橙资源
###图片
http://113.107.160.110:39000/tupian.php?text=千橙资源
###BaseURL
"http://124.223.10.96:8090/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
官方解析
###标题
云海资源
###图片
http://113.107.160.110:39000/tupian.php?text=云海资源
###BaseURL
"http://101.34.7.151:600/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
官方解析
###标题
融兴官采
###图片
http://113.107.160.110:39000/tupian.php?text=融兴官采
###BaseURL
"http://103.222.188.156:99/rongxingapi.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
官方解析
###标题
TIMI资源
###图片
http://113.107.160.110:39000/tupian.php?text=TIMI资源
###BaseURL
"http://api.timizy.top:1005/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
#####
#####优质资源
####
###type
cms
###分类
优质资源
###标题
U酷资源
###图片
http://113.107.160.110:39000/tupian.php?text=U酷资源
###BaseURL
"https://api.ukuapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
优质资源
###标题
淘片资源
###图片
http://113.107.160.110:39000/tupian.php?text=淘片资源
###BaseURL
"https://taopianapi.com/home/cjapi/as/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
优质资源
###标题
一帆资源(VPN)
###图片
http://113.107.160.110:39000/tupian.php?text=一帆资源(VPN)
###BaseURL
"http://api.if101.tv/v1/vod";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
优质资源
###标题
789盘
###图片
http://113.107.160.110:39000/tupian.php?text=789盘
###BaseURL
"https://www.rrvipw.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
优质资源
###标题
爱酷影视
###图片
http://113.107.160.110:39000/tupian.php?text=爱酷影视
###BaseURL
"https://www.zhanlangbu.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
优质资源
###标题
土剧TV
###图片
http://113.107.160.110:39000/tupian.php?text=土剧TV
###BaseURL
"http://tujutv.top/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
优质资源
###标题
ASMR
###图片
http://113.107.160.110:39000/tupian.php?text=ASMR
###BaseURL
"http://www.asmr19.in/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
优质资源
###标题
考拉TV
###图片
http://113.107.160.110:39000/tupian.php?text=考拉TV
###BaseURL
"https://ikaola.tv/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
优质资源
###标题
映迷
###图片
http://113.107.160.110:39000/tupian.php?text=映迷
###BaseURL
"https://www.inmi.app/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
优质资源
###标题
思古影院
###图片
http://113.107.160.110:39000/tupian.php?text=思古影院
###BaseURL
"https://www.siguyy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
优质资源
###标题
乐活影视
###图片
http://113.107.160.110:39000/tupian.php?text=乐活影视
###BaseURL
"https://lehootv.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
优质资源
###标题
ACG动漫
###图片
http://113.107.160.110:39000/tupian.php?text=ACG动漫
###BaseURL
"https://acgcn.ml/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
优质资源
###标题
追剧达人
###图片
http://113.107.160.110:39000/tupian.php?text=ACG动漫
###BaseURL
"http://zjdr.tv/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
#####
#####切片资源
####
###type
cms
###分类
切片资源
###标题
极速BT资源
###图片
http://113.107.160.110:39000/tupian.php?text=极速BT资源
###BaseURL
"https://api.jisubt.com/videos";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
步步高资源
###图片
http://113.107.160.110:39000/tupian.php?text=步步高资源
###BaseURL
"https://api.yparse.com/api/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
金鹰资源
###图片
http://113.107.160.110:39000/tupian.php?text=金鹰资源
###BaseURL
"https://jyzyapi.com/provide/vod";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
官方解析
###标题
iKun资源
###图片
http://113.107.160.110:39000/tupian.php?text=北雁资源
###BaseURL
"https://ikunzyapi.com/api.php/provide/vod";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
极客资源
###图片
http://113.107.160.110:39000/tupian.php?text=极客资源
###BaseURL
"https://jkzy1.com/api.php/provide/vod/from/zkzym3u8/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
星海资源
###图片
http://113.107.160.110:39000/tupian.php?text=星海资源
###BaseURL
"https://www.xhzy01.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
冠军资源
###图片
http://113.107.160.110:39000/tupian.php?text=冠军资源
###BaseURL
"https://www.cmpzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
42资源
###图片
http://113.107.160.110:39000/tupian.php?text=42资源
###BaseURL
"https://www.42.la/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
蘑菇资源
###图片
http://113.107.160.110:39000/tupian.php?text=蘑菇资源
###BaseURL
"http://api.moguapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
1080资源库
###图片
http://113.107.160.110:39000/tupian.php?text=1080资源库
###BaseURL
"https://api.1080zyku.com/inc/api_mac10.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
TOM资源
###图片
http://113.107.160.110:39000/tupian.php?text=TOM资源
###BaseURL
"https://api.tomcaiji.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
快车资源
###图片
http://113.107.160.110:39000/tupian.php?text=快车资源
###BaseURL
"https://caiji.kczyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
松鼠资源
###图片
http://113.107.160.110:39000/tupian.php?text=松鼠资源
###BaseURL
"https://m3u8.songshuzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
多多资源
###图片
http://113.107.160.110:39000/tupian.php?text=多多资源
###BaseURL
"https://www.ddzyz1.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
大眼资源
###图片
http://113.107.160.110:39000/tupian.php?text=大眼资源
###BaseURL
"http://api.dyzy888.com/api/maccms/json/m3u8";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
FOX资源
###图片
http://113.107.160.110:39000/tupian.php?text=FOX资源
###BaseURL
"https://api.foxzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
量子资源
###图片
http://113.107.160.110:39000/tupian.php?text=量子资源
###BaseURL
"http://cj.lziapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
番茄资源
###图片
http://113.107.160.110:39000/tupian.php?text=番茄资源
###BaseURL
"http://api.fqzy.cc/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
卧龙资源
###图片
http://113.107.160.110:39000/tupian.php?text=卧龙资源
###BaseURL
"https://collect.wolongzyw.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
红牛资源
###图片
http://113.107.160.110:39000/tupian.php?text=红牛资源
###BaseURL
"https://www.hongniuzy2.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
樱花资源
###图片
http://113.107.160.110:39000/tupian.php?text=樱花资源
###BaseURL
"https://m3u8.apiyhzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
易看资源
###图片
http://113.107.160.110:39000/tupian.php?text=易看资源
###BaseURL
"https://api.yikanapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
酷点资源
###图片
http://113.107.160.110:39000/tupian.php?text=酷点资源
###BaseURL
"https://kudianzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
速更资源
###图片
http://113.107.160.110:39000/tupian.php?text=速更资源
###BaseURL
"https://sugengzy.cn/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
闪电资源
###图片
http://113.107.160.110:39000/tupian.php?text=闪电资源
###BaseURL
"http://sdzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
飞速资源
###图片
http://113.107.160.110:39000/tupian.php?text=飞速资源
###BaseURL
"https://www.feisuzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
光速资源
###图片
http://113.107.160.110:39000/tupian.php?text=光速资源
###BaseURL
"https://api.guangsuapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
新浪资源
###图片
http://113.107.160.110:39000/tupian.php?text=新浪资源
###BaseURL
"http://api.xinlangapi.com/xinlangapi.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
鱼乐资源
###图片
http://113.107.160.110:39000/tupian.php?text=鱼乐资源
###BaseURL
"https://api.ylzy1.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
韩剧资源
###图片
http://113.107.160.110:39000/tupian.php?text=韩剧资源
###BaseURL
"http://www.hanjuzy.com/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
77韩剧
###图片
http://113.107.160.110:39000/tupian.php?text=77韩剧
###BaseURL
"https://www.77hanju.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
快播资源
###图片
http://113.107.160.110:39000/tupian.php?text=快播资源
###BaseURL
"http://www.kuaibozy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
八戒资源
###图片
http://113.107.160.110:39000/tupian.php?text=八戒资源
###BaseURL
"http://cj.bajiecaiji.com/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
百度资源
###图片
http://113.107.160.110:39000/tupian.php?text=百度资源
###BaseURL
"https://api.apibdzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
无尽资源
###图片
http://113.107.160.110:39000/tupian.php?text=无尽资源
###BaseURL
"https://api.wujinapi.net/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
天空资源
###图片
http://113.107.160.110:39000/tupian.php?text=天空资源
###BaseURL
"https://api.tiankongapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
天翼资源
###图片
http://113.107.160.110:39000/tupian.php?text=天翼资源
###BaseURL
"https://www.911ysw.top/tianyi.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
FF9资源
###图片
http://113.107.160.110:39000/tupian.php?text=FF9资源
###BaseURL
"https://www.ff9.top/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
南国影源
###图片
http://113.107.160.110:39000/tupian.php?text=南国影源
###BaseURL
"http://api.nguonphim.tv/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
看看资源
###图片
http://113.107.160.110:39000/tupian.php?text=看看资源
###BaseURL
"https://zy.hikan.xyz/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
坦克资源
###图片
http://113.107.160.110:39000/tupian.php?text=坦克资源
###BaseURL
"https://tangkzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
#####
#####三方聚合
####
###type
cms
###分类
三方聚合
###标题
影图
###图片
http://113.107.160.110:39000/tupian.php?text=影图
###BaseURL
"https://cj.vodimg.top/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
飘零影院
###图片
http://113.107.160.110:39000/tupian.php?text=飘零影院
###BaseURL
"https://p2100.net/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
爱兜视频
###图片
http://113.107.160.110:39000/tupian.php?text=爱兜视频
###BaseURL
"http://id190.tpddns.cn:81/mogai_api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
瞬间影视
###图片
http://113.107.160.110:39000/tupian.php?text=瞬间影视
###BaseURL
"http://app.7en7.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
臭弟弟资源
###图片
http://113.107.160.110:39000/tupian.php?text=臭弟弟资源
###BaseURL
"https://www.choudidi.top/zyapi.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
干饭影视
###图片
http://113.107.160.110:39000/tupian.php?text=干饭影视
###BaseURL
"http://124.220.183.81:83/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
票厂影视
###图片
http://113.107.160.110:39000/tupian.php?text=票厂影视
###BaseURL
"http://101.43.119.105/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
天天影视
###图片
http://113.107.160.110:39000/tupian.php?text=天天影视
###BaseURL
"http://tttv.cf/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
创艺影视
###图片
http://113.107.160.110:39000/tupian.php?text=创艺影视
###BaseURL
"https://www.30dian.cn/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
香瓜影视
###图片
http://113.107.160.110:39000/tupian.php?text=香瓜影视
###BaseURL
"http://v.xgvod.top/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
火星影视
###图片
http://113.107.160.110:39000/tupian.php?text=火星影视
###BaseURL
"http://47.102.85.40/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
MX影院
###图片
http://113.107.160.110:39000/tupian.php?text=MX影院
###BaseURL
"http://49.235.107.145:81/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
幻风影视
###图片
http://113.107.160.110:39000/tupian.php?text=幻风影视
###BaseURL
"http://vip857.top/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
小鸟动漫
###图片
http://113.107.160.110:39000/tupian.php?text=小鸟动漫
###BaseURL
"http://xydm.baicai.buzz/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
蜗牛动漫
###图片
http://113.107.160.110:39000/tupian.php?text=蜗牛动漫
###BaseURL
"http://woniudm.woniu.cyou:20000/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
海玉影视
###图片
http://113.107.160.110:39000/tupian.php?text=海玉影视
###BaseURL
"http://tv2.hykjtv.cn/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
百淘影视
###图片
http://113.107.160.110:39000/tupian.php?text=百淘影视
###BaseURL
"http://ys.58g8.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
阿里影视
###图片
http://113.107.160.110:39000/tupian.php?text=阿里影视
###BaseURL
"http://aliys.cn:90/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
醉璃笙TV
###图片
http://113.107.160.110:39000/tupian.php?text=醉璃笙TV
###BaseURL
"http://web.xhdj.vip/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
热剧天堂
###图片
http://113.107.160.110:39000/tupian.php?text=热剧天堂
###BaseURL
"http://175.178.7.35:2020/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
贵宾影院
###图片
http://113.107.160.110:39000/tupian.php?text=贵宾影院
###BaseURL
"http://vipdytv.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
趣看
###图片
http://113.107.160.110:39000/tupian.php?text=趣看
###BaseURL
"https://qkmp4.cn/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
39影视
###图片
http://113.107.160.110:39000/tupian.php?text=39影视
###BaseURL
"https://www.39kan.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
飘花电影
###图片
http://113.107.160.110:39000/tupian.php?text=飘花电影
###BaseURL
"http://www.zzrhgg.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
千寻时光
###图片
http://113.107.160.110:39000/tupian.php?text=千寻时光
###BaseURL
"http://wy.dqyhg.cn/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
网民电影
###图片
http://113.107.160.110:39000/tupian.php?text=网民电影
###BaseURL
"https://www.prinevillesda.org/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
MBO影视
###图片
http://113.107.160.110:39000/tupian.php?text=MBO影视
###BaseURL
"https://www.mbomovie.com/api.php/provide/vod/at/xml/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
海外电影
###图片
http://113.107.160.110:39000/tupian.php?text=海外电影
###BaseURL
"https://www.200121.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
#####
#####18+
####
###type
cms
###分类
18+
###标题
523资源
###图片
http://113.107.160.110:39000/tupian.php?text=523资源
###BaseURL
"https://caiji.523zyw.com/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
155资源
###图片
http://113.107.160.110:39000/tupian.php?text=155资源
###BaseURL
"https://155api.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
丝袜资源
###图片
http://113.107.160.110:39000/tupian.php?text=丝袜资源
###BaseURL
"https://siwazyw.cc/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
芒果资源
###图片
http://113.107.160.110:39000/tupian.php?text=芒果资源
###BaseURL
"https://mgzyz1.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
乐鱼资源
###图片
http://113.107.160.110:39000/tupian.php?text=乐鱼资源
###BaseURL
"https://www.leyuzyapi.com/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
水蜜桃
###图片
http://113.107.160.110:39000/tupian.php?text=水蜜桃
###BaseURL
"https://smt999.cc/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
三级片资源
###图片
http://113.107.160.110:39000/tupian.php?text=三级片资源
###BaseURL
"https://caiji.jjjzy.cc/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
花色资源
###图片
http://113.107.160.110:39000/tupian.php?text=花色资源
###BaseURL
"https://api.huasezy.xyz/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
探探资源
###图片
http://113.107.160.110:39000/tupian.php?text=探探资源
###BaseURL
"https://apittzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
秀色资源
###图片
http://113.107.160.110:39000/tupian.php?text=秀色资源
###BaseURL
"https://api.xiuseapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
色猫资源
###图片
http://113.107.160.110:39000/tupian.php?text=色猫资源
###BaseURL
"https://api.maozyapi.com/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
草莓资源
###图片
http://113.107.160.110:39000/tupian.php?text=草莓资源
###BaseURL
"https://caiji.caomeiapi.com/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
草莓2
###图片
http://113.107.160.110:39000/tupian.php?text=草莓2
###BaseURL
"http://192.154.101.146:8888/inc/api.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
花魁资源
###图片
http://113.107.160.110:39000/tupian.php?text=花魁资源
###BaseURL
"https://caiji.huakuiapi.com/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
葡萄资源
###图片
http://113.107.160.110:39000/tupian.php?text=葡萄资源
###BaseURL
"https://api.putaozy.net/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
色窝资源
###图片
http://113.107.160.110:39000/tupian.php?text=色窝资源
###BaseURL
"https://sewozyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
淫窝资源
###图片
http://113.107.160.110:39000/tupian.php?text=淫窝资源
###BaseURL
"https://api.yinwoapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
国色资源
###图片
http://113.107.160.110:39000/tupian.php?text=国色资源
###BaseURL
"https://api.guosezy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
金莲资源
###图片
http://113.107.160.110:39000/tupian.php?text=金莲资源
###BaseURL
"https://111kkkkk.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
皇冠资源
###图片
http://113.107.160.110:39000/tupian.php?text=皇冠资源
###BaseURL
"https://hghhh.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
热巴资源
###图片
http://113.107.160.110:39000/tupian.php?text=热巴资源
###BaseURL
"http://reba.aishunxs.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
狼友资源
###图片
http://113.107.160.110:39000/tupian.php?text=狼友资源
###BaseURL
"https://www.langyouzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
鸡霸资源
###图片
http://113.107.160.110:39000/tupian.php?text=鸡霸资源
###BaseURL
"https://api.jibaapi.cc/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
滴滴资源
###图片
http://113.107.160.110:39000/tupian.php?text=滴滴资源
###BaseURL
"https://api.ddapi.cc/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
香蕉视频
###图片
http://113.107.160.110:39000/tupian.php?text=香蕉视频
###BaseURL
"https://ea111.cc/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
雪豹资源
###图片
http://113.107.160.110:39000/tupian.php?text=雪豹资源
###BaseURL
"https://api.xbapi.cc/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
森林资源
###图片
http://113.107.160.110:39000/tupian.php?text=森林资源
###BaseURL
"https://slapibf.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
玉兔资源
###图片
http://113.107.160.110:39000/tupian.php?text=玉兔资源
###BaseURL
"https://apiyutu.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
奥斯卡资源
###图片
http://113.107.160.110:39000/tupian.php?text=奥斯卡资源
###BaseURL
"https://aosikazy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
色南国资源
###图片
http://113.107.160.110:39000/tupian.php?text=色南国资源
###BaseURL
"https://api.sexnguon.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
3366资源
###图片
http://113.107.160.110:39000/tupian.php?text=3366资源
###BaseURL
"http://www.3366zy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
色屌丝资源
###图片
http://113.107.160.110:39000/tupian.php?text=色屌丝资源
###BaseURL
"http://sdszyapi.com/home/cjapi/asbb/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
小姐姐资源
###图片
http://113.107.160.110:39000/tupian.php?text=小姐姐资源
###BaseURL
"https://xjjzyapi.com/home/cjapi/askl/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
52AVAV
###图片
http://113.107.160.110:39000/tupian.php?text=52AVAV
###BaseURL
"https://52zyapi.com/home/cjapi/asda/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
我要啪啪
###图片
http://113.107.160.110:39000/tupian.php?text=我要啪啪
###BaseURL
"http://www.caiji21.com/home/cjapi/klkl/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
AV集中淫
###图片
http://113.107.160.110:39000/tupian.php?text=AV集中淫
###BaseURL
"https://www.caiji22.com/home/cjapi/klp0/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
夜夜撸资源
###图片
http://113.107.160.110:39000/tupian.php?text=夜夜撸资源
###BaseURL
"https://www.caiji23.com/home/cjapi/kls6/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
大屌丝资源
###图片
http://113.107.160.110:39000/tupian.php?text=大屌丝资源
###BaseURL
"http://www.caiji24.com/home/cjapi/p0d2/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
咪咪资源
###图片
http://113.107.160.110:39000/tupian.php?text=咪咪资源
###BaseURL
"http://www.caiji25.com/home/cjapi/p0as/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
鲍鱼AV
###图片
http://113.107.160.110:39000/tupian.php?text=鲍鱼AV
###BaseURL
"http://caiji26.com/home/cjapi/p0g8/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
精工厂资源
###图片
http://113.107.160.110:39000/tupian.php?text=精工厂资源
###BaseURL
"https://jgczyapi.com/home/cjapi/kld2/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
点点娱乐
###图片
http://113.107.160.110:39000/tupian.php?text=点点娱乐
###BaseURL
"https://xx55zyapi.com/home/cjapi/ascf/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
大MM资源
###图片
http://113.107.160.110:39000/tupian.php?text=大MM资源
###BaseURL
"https://www.dmmapi.com/home/cjapi/asd2c7/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
老司鸡资源
###图片
http://113.107.160.110:39000/tupian.php?text=老司鸡资源
###BaseURL
"https://www.lsjapi.com/home/cjapi/asd2g8/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
黄瓜TV资源
###图片
http://113.107.160.110:39000/tupian.php?text=黄瓜TV资源
###BaseURL
"https://www.caiji10.com/home/cjapi/cfs6/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
快播盒子资源
###图片
http://113.107.160.110:39000/tupian.php?text=快播盒子资源
###BaseURL
"https://www.caiji09.com/home/cjapi/cfp0/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
大香蕉资源
###图片
http://113.107.160.110:39000/tupian.php?text=大香蕉资源
###BaseURL
"https://www.caiji08.com/home/cjapi/cfkl/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
日本AV在线
###图片
http://113.107.160.110:39000/tupian.php?text=日本AV在线
###BaseURL
"https://www.caiji07.com/home/cjapi/cfcf/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
青青草视频
###图片
http://113.107.160.110:39000/tupian.php?text=青青草视频
###BaseURL
"https://www.caiji05.com/home/cjapi/cfda/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
麻豆视频
###图片
http://113.107.160.110:39000/tupian.php?text=麻豆视频
###BaseURL
"https://www.caiji04.com/home/cjapi/cfc7/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
一本道资源
###图片
http://113.107.160.110:39000/tupian.php?text=一本道资源
###BaseURL
"https://www.caiji03.com/home/cjapi/cfg8/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
草榴视频
###图片
http://113.107.160.110:39000/tupian.php?text=草榴视频
###BaseURL
"https://www.caiji02.com/home/cjapi/cfas/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
亚洲成人在线
###图片
http://113.107.160.110:39000/tupian.php?text=亚洲成人在线
###BaseURL
"https://www.caiji01.com/home/cjapi/cfd2/mc10/vod/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
天噜啦资源
###图片
http://113.107.160.110:39000/tupian.php?text=天噜啦资源
###BaseURL
"http://www.987caiji.com/api/max.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
99资源
###图片
http://113.107.160.110:39000/tupian.php?text=99资源
###BaseURL
"http://99zy.pw/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
010爱资源
###图片
http://113.107.160.110:39000/tupian.php?text=010爱资源
###BaseURL
"http://www.010aizy.com/API/macs.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
抖阴视频
###图片
http://113.107.160.110:39000/tupian.php?text=抖阴视频
###BaseURL
"https://www.888dav.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
麻豆视频
###图片
http://113.107.160.110:39000/tupian.php?text=麻豆视频
###BaseURL
"http://www.madouse.la/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
蛋蛋视频
###图片
http://113.107.160.110:39000/tupian.php?text=蛋蛋视频
###BaseURL
"http://156.249.29.8/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
91麻豆
###图片
http://113.107.160.110:39000/tupian.php?text=91麻豆
###BaseURL
"https://91md.me/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
浪潮资源
###图片
http://113.107.160.110:39000/tupian.php?text=浪潮资源
###BaseURL
"http://langchaozy11.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
酷豆资源
###图片
http://113.107.160.110:39000/tupian.php?text=酷豆资源
###BaseURL
"https://kudouzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
酷豆2
###图片
http://113.107.160.110:39000/tupian.php?text=酷豆2
###BaseURL
"https://api.kdapi.info/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
酷伦理
###图片
http://113.107.160.110:39000/tupian.php?text=酷伦理
###BaseURL
"https://api.kudian70.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
影库资源
###图片
http://113.107.160.110:39000/tupian.php?text=影库资源
###BaseURL
"https://api.ykapi.net/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
奶茶资源
###图片
http://113.107.160.110:39000/tupian.php?text=奶茶资源
###BaseURL
"https://caiji.naichaapi.com/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
爱播资源
###图片
http://113.107.160.110:39000/tupian.php?text=爱播资源
###BaseURL
"https://cj.apiabzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
美少女资源
###图片
http://113.107.160.110:39000/tupian.php?text=美少女资源
###BaseURL
"https://www.msnii.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
淫水机资源
###图片
http://113.107.160.110:39000/tupian.php?text=淫水机资源
###BaseURL
"https://www.xrbsp.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
香奶儿资源
###图片
http://113.107.160.110:39000/tupian.php?text=香奶儿资源
###BaseURL
"https://www.gdlsp.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
白嫖资源
###图片
http://113.107.160.110:39000/tupian.php?text=白嫖资源
###BaseURL
"https://www.kxgav.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
小湿妹资源
###图片
http://113.107.160.110:39000/tupian.php?text=小湿妹资源
###BaseURL
"https://www.afasu.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
黄AV资源
###图片
http://113.107.160.110:39000/tupian.php?text=黄AV资源
###BaseURL
"https://www.pgxdy.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
大地资源
###图片
http://113.107.160.110:39000/tupian.php?text=大地资源
###BaseURL
"https://dadiapi.com/api.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
CK资源
###图片
http://113.107.160.110:39000/tupian.php?text=CK资源
###BaseURL
"http://www.feifei67.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
老鸭资源
###图片
http://113.107.160.110:39000/tupian.php?text=老鸭资源
###BaseURL
"https://api.apilyzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
辣椒资源
###图片
http://113.107.160.110:39000/tupian.php?text=辣椒资源
###BaseURL
"https://apilj.com/api.php/provide/vod/at/json/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
乐播资源
###图片
http://113.107.160.110:39000/tupian.php?text=乐播资源
###BaseURL
"https://lbapi9.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
博天堂
###图片
http://113.107.160.110:39000/tupian.php?text=博天堂
###BaseURL
"http://bttcj.com/inc/sapi.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
环亚资源
###图片
http://113.107.160.110:39000/tupian.php?text=环亚资源
###BaseURL
"http://wmcj8.com/inc/sapi.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
JAV名优馆
###图片
http://113.107.160.110:39000/tupian.php?text=JAV名优馆
###BaseURL
"http://mygzycj.com/api.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
色色资源
###图片
http://113.107.160.110:39000/tupian.php?text=色色资源
###BaseURL
"http://secj8.com/inc/sapi.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
玖玖资源
###图片
http://113.107.160.110:39000/tupian.php?text=玖玖资源
###BaseURL
"http://99zywcj.com/inc/sapi.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
久草资源
###图片
http://113.107.160.110:39000/tupian.php?text=久草资源
###BaseURL
"http://jcspcj8.com/api";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
狼少年
###图片
http://113.107.160.110:39000/tupian.php?text=狼少年
###BaseURL
"http://cjmygzy.com/inc/sapi.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
富二代资源
###图片
http://113.107.160.110:39000/tupian.php?text=富二代资源
###BaseURL
"http://f2dcj6.com/sapi";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
字幕网
###图片
http://113.107.160.110:39000/tupian.php?text=字幕网
###BaseURL
"http://zmcj88.com/sapi";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
利来资源
###图片
http://113.107.160.110:39000/tupian.php?text=利来资源
###BaseURL
"http://llzxcj.com/inc/sck.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
佳丽资源
###图片
http://113.107.160.110:39000/tupian.php?text=佳丽资源
###BaseURL
"http://www.jializyzapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
香蕉资源(佳丽)
###图片
http://113.107.160.110:39000/tupian.php?text=香蕉资源(佳丽)
###BaseURL
"https://xjzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
番号资源
###图片
http://113.107.160.110:39000/tupian.php?text=番号资源
###BaseURL
"http://fhapi9.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
鲨鱼资源
###图片
http://113.107.160.110:39000/tupian.php?text=鲨鱼资源
###BaseURL
"https://shayuapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
速度资源
###图片
http://113.107.160.110:39000/tupian.php?text=速度资源
###BaseURL
"http://www.ggmmzy.com:9999/inc/xml";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
18+
###标题
KK写真资源
###图片
http://113.107.160.110:39000/tupian.php?text=KK写真资源
###BaseURL
"https://kkzy.me/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
#####
#####诈尸
####
###type
cms
###分类
诈尸
###标题
椰子资源
###图片
http://113.107.160.110:39000/tupian.php?text=椰子资源
###BaseURL
"https://zy.gbxy.net.cn/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
椰子资源
###图片
http://113.107.160.110:39000/tupian.php?text=椰子资源
###BaseURL
"http://lb.gbxy.net.cn/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
麒麟资源
###图片
http://113.107.160.110:39000/tupian.php?text=麒麟资源
###BaseURL
"https://www.qilinzyz.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
星河资源
###图片
http://113.107.160.110:39000/tupian.php?text=星河资源
###BaseURL
"https://api.iniki.cn/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
M3U8.TV资源
###图片
http://113.107.160.110:39000/tupian.php?text=M3U8.TV资源
###BaseURL
"http://www.zycaiji.net:7788/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
雨哥哥影视
###图片
http://113.107.160.110:39000/tupian.php?text=雨哥哥影视
###BaseURL
"http://cj.baozi66.top:66/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
8090资源
###图片
http://113.107.160.110:39000/tupian.php?text=8090资源
###BaseURL
"http://zy.yilans.net/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
八戒官采
###图片
http://113.107.160.110:39000/tupian.php?text=八戒官采
###BaseURL
"https://www.bajiezy.xyz/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
开放云(X5)
###图片
http://113.107.160.110:39000/tupian.php?text=开放云(X5)
###BaseURL
"https://z.iopenyun.com:99/apiopy.php/provide/vod/from/Tcm3u8/?ac=list";
###首页地址
getVar("baseURL")+"&ac=list&pg=1";
###分类地址
getVar("baseURL")+"&ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"&wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
英皇官采
###图片
http://113.107.160.110:39000/tupian.php?text=英皇官采
###BaseURL
"http://api.travelbooking.cc/xml";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
BL视频
###图片
http://113.107.160.110:39000/tupian.php?text=BL视频
###BaseURL
"https://bljiex.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
OmoFun
###图片
http://113.107.160.110:39000/tupian.php?text=OmoFun
###BaseURL
"https://app.omofun.net/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
Mux切片
###图片
http://113.107.160.110:39000/tupian.php?text=Mux切片
###BaseURL
"https://muxnb.muxvip.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
MuX2
###图片
http://113.107.160.110:39000/tupian.php?text=MuX2
###BaseURL
"https://video.muxvip.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
思古切片
###图片
http://113.107.160.110:39000/tupian.php?text=思古切片
###BaseURL
"https://cai.gbxy.net.cn/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
奈飞云
###图片
http://113.107.160.110:39000/tupian.php?text=奈飞云
###BaseURL
"http://45.125.46.41:4433/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
木子看剧
###图片
http://113.107.160.110:39000/tupian.php?text=木子看剧
###BaseURL
"https://mzkj.maccms.cf/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
奈菲迷
###图片
http://113.107.160.110:39000/tupian.php?text=奈菲迷
###BaseURL
"https://app.netflixmi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
影世界
###图片
http://113.107.160.110:39000/tupian.php?text=影世界
###BaseURL
"https://video.yingworld.vip/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
鸭奈飞
###图片
http://113.107.160.110:39000/tupian.php?text=鸭奈飞
###BaseURL
"http://newtv.yanaifei.cn/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
鸭奈飞
###图片
http://113.107.160.110:39000/tupian.php?text=鸭奈飞
###BaseURL
"http://106.13.199.87:4433/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
人人迷蓝光
###图片
http://113.107.160.110:39000/tupian.php?text=人人迷蓝光
###BaseURL
"https://koko.renrenmi.cc/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
龙腾资源
###图片
http://113.107.160.110:39000/tupian.php?text=龙腾资源
###BaseURL
"http://175.178.7.35:2020/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
花椒资源
###图片
http://113.107.160.110:39000/tupian.php?text=花椒资源
###BaseURL
"https://apihjzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
4000资源
###图片
http://113.107.160.110:39000/tupian.php?text=4000资源
###BaseURL
"http://4000zy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
61783
###图片
http://113.107.160.110:39000/tupian.php?text=61783
###BaseURL
"https://61783.xyz/api.php/provide/art/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
爱看资源
###图片
http://113.107.160.110:39000/tupian.php?text=爱看资源
###BaseURL
"http://www.aikanzyz9.com/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
诈尸
###标题
AVZY898资源
###图片
http://113.107.160.110:39000/tupian.php?text=AVZY898资源
###BaseURL
"http://avzy898.com/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
#####